apiVersion: apps/v1
kind: Deployment
metadata:
  name: semaphore-service-mirror
  labels:
    app: semaphore-service-mirror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semaphore-service-mirror
  template:
    metadata:
      labels:
        app: semaphore-service-mirror
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: semaphore-service-mirror
      containers:
        - name: semaphore-service-mirror
          image: semaphore-service-mirror
          env:
            - name: SSM_CONFIG
              value: "/etc/semaphore-service-mirror/config.json"
          volumeMounts:
            - name: config
              mountPath: /etc/semaphore-service-mirror/
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
            failureThreshold: 6
            initialDelaySeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
      volumes:
        - name: config
          configMap:
            name: semaphore-service-mirror-config
