apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - rbac.yaml
images:
  - name: semaphore-service-mirror
    newName: quay.io/utilitywarehouse/semaphore-service-mirror
    newTag: v0.4.2
