# Cluster role and serviceaccount to be used by remote instances of
# semaphore-service-mirror in order to be able to mirror from this cluster
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: semaphore-service-mirror-remote
rules:
  - apiGroups: [""]
    resources:
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: semaphore-service-mirror-remote
subjects:
  - kind: ServiceAccount
    name: semaphore-service-mirror-remote
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: semaphore-service-mirror-remote
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: semaphore-service-mirror-remote
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: semaphore-service-mirror-remote-token
  annotations:
    kubernetes.io/service-account.name: semaphore-service-mirror-remote
type: kubernetes.io/service-account-token
