apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - rbac.yaml
configMapGenerator:
  - name: semaphore-service-mirror-config
    files:
     - config.json=resources/semaphore-service-mirror-config.json
secretGenerator:
  - name: remote-kube-token
    type: Opaque
    files:
      - token=secrets/remote-kube-token
images:
  - name: semaphore-service-mirror
    newName: quay.io/utilitywarehouse/semaphore-service-mirror
    newTag: master
