apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../kustomize/namespaced/
patchesStrategicMerge:
  - deployment-patch.yaml
configMapGenerator:
  - name: semaphore-service-mirror-config
    files:
     - config.json=resources/semaphore-service-mirror-config.json
secretGenerator:
  - name: remote-kube-token
    type: Opaque
    files:
      - token=secrets/remote-kube-token
